Algoritmo "conteAte10"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/06/2025
Var
// Seção de Declarações das variáveis 
   contador: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   contador <- 0
   Enquanto (contador <= 5) faca
            EscrevaL(contador)
            contador <- contador + 1
   FimEnquanto
   EscrevaL("Terminei de contar")
Fimalgoritmo