Algoritmo "conversor"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/06/2025
Var
// Seção de Declarações das variáveis 
   angulo, S: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva ("Informe um angulo: ")
   Leia (angulo)
   S <- Sen(GraupRad(angulo))
   Escreva ("O seno de ", angulo, " e igual a ",S)

Fimalgoritmo