Algoritmo "Creuza03"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/06/2025
Var
// Seção de Declarações das variáveis 
   F, C: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Qual e a temperatura aqui? ")
   Leia(F)
   C <- (F - 32) / 1.8
   Escreval("A temperatura aqui no Brasil ", C:4:1)

Fimalgoritmo