Algoritmo "Creuza02"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/06/2025
Var
// Seção de Declarações das variáveis 
   reais, dolares: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Quantos Reais eu tenho? ")
   Leia(reais)
   dolares <- reais/2.20
   Escreval("Posso ter US$ ",dolares)

Fimalgoritmo