Algoritmo "ParOuImpar"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/06/2025
Var
   // Seção de Declarações das variáveis
   N: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Digite um número qualquer? ")
   Leia(N)
   Se (N % 2 = 0) entao
      Escreval("O número ", N , " e PAR")
   senao
      Escreval("O número ", N , " e IMPAR")
   Fimse

Fimalgoritmo